version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/server
    ports:
      - 8000:80

  app:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 5000:80
    command: python3 server.py
    