version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/server
    ports:
      - 8000:80

  app:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 5000:80
    command: uvicorn brew_app.main:app
